### ISSUE TITLE
User info not saved correctly

### ISSUE THREAD

**Issue by loui981c** [Educado-App/educado-mobile#111]
## Issue Description

When logging into the app, the user info is not saved to AsyncStorage correctly. Also, it doesn't check if all the fields (id, firstName, lastName, email) that should be in userInfo are not null or if they match the data from the database. Currently, it only saves the information correctly when registering a new user. However, if the user logs in on another phone, the data would be incorrect since the AsyncStorage would be empty.

Consider refactoring the code so that all functions using AsyncStorage and variables as USER_INFO are in StorageService.js, gathering them in one place.

## Steps to Reproduce

1. Register a new user
2. Log in on another device or clear AsyncStorage
3. Check when fetching the userInfo that it returns the correct data 

## Expected Behavior

That the userInfo should always contain the data from DB when logging in and stores it correctly in AsyncStorage

## Actual Behavior

No userInfo is updated, cleared or saved when logging in and out

## Additional Information

The following files contains the USER_INFO variable but never uses it:
- LogOutButton.js (needs to clear the userInfo)
- LoginForm.js (needs to update the userInfo)

There is also a misleading console.log in loginUser at userApi.js and the function in RegisterForm.js is also called LoginForm fyi

**Comment by Havkost** [comment]
Hmm.. It works for me running dev on both frontend and backend.
- On which branches are you experiencing this issue?
- Which user are you logging into? - do they have `firstName` and `lastName` instead of the older `name`?

I agree that it'd be better to move the saveUserInfoLocally functions into storageService, we'll get on that tomorrow.

I did spot a small error in the backend, firstName was being set to name, which is no longer a field - I'll make a hotfix commit to dev for this. This does not seem to be the source of your issue though, as it was still setting userInfo, but with firstName as undefined.

We implemented userInfo for some of your PBIs, so we're expecting that you'll bring along these changes to staging when those PBIs are ready 👍
