### ISSUE TITLE
[App - Virtual Tutor] User feedback for the AI response

### ISSUE THREAD

**Issue by iarandrd** [Educado-App/educado-mobile#374]

**Comment by sigurdthecoder** [comment]
Acceptance criteria: 
- The user gets the option to "thumbs up" each response provided by Edu. 

- Every time a user "thumbs up" a response from Edu, the information regarding that response will be saved to the database. 

- The database entries are easily reformatted so that Edu manually can be fed the new training data and improve from the user feedback.
